stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .stack-work

test:
  stage: test
  image: pavelkucera/thesis:lts-13.17
  script:
    - stack test --color always --test-arguments=--color

hlint:
  stage: test
  image: pavelkucera/thesis:lts-13.17
  script:
    - hlint src
