stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .stack-work

services:
  - name: pavelkucera/thesis-postgres:11.2-alpine
    alias: postgres

variables:
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

test:
  stage: test
  image: pavelkucera/thesis:lts-13.17
  script:
    - stack test --color always --test-arguments=--color

hlint:
  stage: test
  image: pavelkucera/thesis:lts-13.17
  script:
    - hlint src
