name: thesis
github: pavelkucera/thesis
author:
  - Pavel Kucera <pave.kucera@gmail.com>
  - Leendert Bastiaan van Doorn <xbt504@alumni.ku.dk>
maintainer:
  - Pavel Kucera <pave.kucera@gmail.com>
  - Leendert Bastiaan van Doorn <xbt504@alumni.ku.dk>
license: MIT

extra-source-files:
  - LICENSE
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - deepseq
  - exceptions
  - megaparsec
  - mtl
  - parser-combinators
  - postgresql-simple
  - random
  - text
  - scientific
  - template-haskell

library:
  source-dirs: src

tests:
  spec:
    source-dirs:
      - test
      - src
    main: Spec.hs
    default-extensions:
      - ScopedTypeVariables
    ghc-options:
      - -Wno-type-defaults
      - -Wno-incomplete-uni-patterns
      - -Wno-name-shadowing
    build-tools: hspec-discover
    dependencies:
      - hspec
      - hspec-discover
      - hspec-megaparsec
      - QuickCheck
      - quickcheck-instances
